Copy and style changes
UKGovernmentBEIS/payment-practices-reporting pull request #50
Opened 2017-08-16 16:32 UTC by techbelly

2017-08-16 22:18 UTC, DougC commented
I've created a review app for this PR on Heroku at https://beis-ppr-dev-pr-50.herokuapp.com which you can use to check the changes look right.

2017-08-31 09:47 UTC, dgmstuart requested changes
Alex Jackson communicated some changes that need to be reverted here. I'll progress them.

2017-08-31 09:47 UTC, dgmstuart commented on src/main/twirl/views/questionnaire/start.scala.html
> +        Every business within the group will need to do this individually.
The copy change is correct, but they've done usability testing which says that people missed this block

Solution: apply the previous formatting applied to this block: panel and bold

2017-08-31 09:47 UTC, dgmstuart commented on src/main/twirl/views/shared/_coverageInformation.scala.html
> -    If a UK law (i.e. the law of England and Wales, Scotland or Northern Ireland) applies to a contract without the parties
Everything from here below will take longer to sign off and therefore should be in a separate PR

2017-08-31 09:47 UTC, dgmstuart commented on src/main/twirl/views/shared/_day1Calculation.scala.html
> +Day 1 for calculation purposes is the day after receipt - whatever day of the week that is, including weekends and bank holidays. <br />
Remove "and bank holidays"

2017-08-31 10:04 UTC, dgmstuart commented
I pulled down the latest changes from master onto our fork and rebased this PR on top of that

2017-08-31 10:06 UTC, DougC commented
@dgmstuart I've invited you as a collaborator on this repo so you can work directly and avoid all the hassle with updating your fork.

2017-08-31 10:30 UTC, dgmstuart commented
@DougC ah thanks - hopefully we're good now, but if further changes need to be made then we can re-create these changes on the main project and raise a new PR directly (instead of from the fork).

2017-08-31 11:47 UTC, DougC approved these changes
Corinne has confirmed she's happy for these changes to be merged

2017-08-31 12:03 UTC, dgmstuart commented
Great - thanks for merging Doug. I figure if those other changes do get approved later then you can just do a git revert on the commits where I removed them. 

Hope that makes sense!

Duncan Stuart

On Thu, 31 Aug 2017 at 12:47 Doug Clinton

<
mailto:Doug Clinton <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

@DougC

approved this pull request.

Corinne has confirmed she's happy for these changes to be merged

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/UKGovernmentBEIS/payment-practices-reporting/pull/50#pullrequestreview-59832474
, or
https://github.com/notifications/unsubscribe-auth/AAX_z6iau-kEMlTOu_ugzITNhyiM_WdJks5sdp08gaJpZM4O5K4K
.

2017-08-31 12:05 UTC, DougC commented
@dgmstuart I'd rather not get involved in that, to be honest  :-) I'm not sure which changes you mean, but best if you pull them onto another PR as and when they're needed.

2017-08-31 12:08 UTC, merged